### ISSUE TITLE
Can u send working example of this library

### ISSUE THREAD

**Issue by gaurav-bothra** [kevinmarx/viewstate#3]

**Comment by kevinmarx** [comment]
You can initialize Viewstate in your base view and pass it to child views in the initialize method.
```
initialize: function(options) {
    this.viewstate = options.viewstate
}
```

You can then subscribe to the various state changes this view is concerned with.
```
initialize: function(options) {
  this.viewstate = options.viewstate
  this.viewstate.on('change:stateName', this.render, this)
}
```

I am no longer maintaining this project as I have been using React and Vue.js which implement this functionality already. I recommend looking at those projects.

**Comment by gaurav-bothra** [comment]
can u send me proper example
